// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.3.0
// - protoc             (unknown)
// source: wasmapp/onchainkeeper/tx.proto

package onchainkeeper

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

const (
	Msg_UpdateParams_FullMethodName           = "/wasmapp.onchainkeeper.Msg/UpdateParams"
	Msg_RegisterCronContract_FullMethodName   = "/wasmapp.onchainkeeper.Msg/RegisterCronContract"
	Msg_UnregisterCronContract_FullMethodName = "/wasmapp.onchainkeeper.Msg/UnregisterCronContract"
	Msg_ActivateCronContract_FullMethodName   = "/wasmapp.onchainkeeper.Msg/ActivateCronContract"
)

// MsgClient is the client API for Msg service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type MsgClient interface {
	// UpdateParams defines a (governance) operation for updating the module
	// parameters. The authority defaults to the x/gov module account.
	UpdateParams(ctx context.Context, in *MsgUpdateParams, opts ...grpc.CallOption) (*MsgUpdateParamsResponse, error)
	RegisterCronContract(ctx context.Context, in *MsgRegisterCronContract, opts ...grpc.CallOption) (*MsgRegisterCronContractResponse, error)
	UnregisterCronContract(ctx context.Context, in *MsgUnregisterCronContract, opts ...grpc.CallOption) (*MsgUnregisterCronContractResponse, error)
	ActivateCronContract(ctx context.Context, in *MsgActivateCronContract, opts ...grpc.CallOption) (*MsgActivateCronContractResponse, error)
}

type msgClient struct {
	cc grpc.ClientConnInterface
}

func NewMsgClient(cc grpc.ClientConnInterface) MsgClient {
	return &msgClient{cc}
}

func (c *msgClient) UpdateParams(ctx context.Context, in *MsgUpdateParams, opts ...grpc.CallOption) (*MsgUpdateParamsResponse, error) {
	out := new(MsgUpdateParamsResponse)
	err := c.cc.Invoke(ctx, Msg_UpdateParams_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *msgClient) RegisterCronContract(ctx context.Context, in *MsgRegisterCronContract, opts ...grpc.CallOption) (*MsgRegisterCronContractResponse, error) {
	out := new(MsgRegisterCronContractResponse)
	err := c.cc.Invoke(ctx, Msg_RegisterCronContract_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *msgClient) UnregisterCronContract(ctx context.Context, in *MsgUnregisterCronContract, opts ...grpc.CallOption) (*MsgUnregisterCronContractResponse, error) {
	out := new(MsgUnregisterCronContractResponse)
	err := c.cc.Invoke(ctx, Msg_UnregisterCronContract_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *msgClient) ActivateCronContract(ctx context.Context, in *MsgActivateCronContract, opts ...grpc.CallOption) (*MsgActivateCronContractResponse, error) {
	out := new(MsgActivateCronContractResponse)
	err := c.cc.Invoke(ctx, Msg_ActivateCronContract_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// MsgServer is the server API for Msg service.
// All implementations must embed UnimplementedMsgServer
// for forward compatibility
type MsgServer interface {
	// UpdateParams defines a (governance) operation for updating the module
	// parameters. The authority defaults to the x/gov module account.
	UpdateParams(context.Context, *MsgUpdateParams) (*MsgUpdateParamsResponse, error)
	RegisterCronContract(context.Context, *MsgRegisterCronContract) (*MsgRegisterCronContractResponse, error)
	UnregisterCronContract(context.Context, *MsgUnregisterCronContract) (*MsgUnregisterCronContractResponse, error)
	ActivateCronContract(context.Context, *MsgActivateCronContract) (*MsgActivateCronContractResponse, error)
	mustEmbedUnimplementedMsgServer()
}

// UnimplementedMsgServer must be embedded to have forward compatible implementations.
type UnimplementedMsgServer struct {
}

func (UnimplementedMsgServer) UpdateParams(context.Context, *MsgUpdateParams) (*MsgUpdateParamsResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method UpdateParams not implemented")
}
func (UnimplementedMsgServer) RegisterCronContract(context.Context, *MsgRegisterCronContract) (*MsgRegisterCronContractResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method RegisterCronContract not implemented")
}
func (UnimplementedMsgServer) UnregisterCronContract(context.Context, *MsgUnregisterCronContract) (*MsgUnregisterCronContractResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method UnregisterCronContract not implemented")
}
func (UnimplementedMsgServer) ActivateCronContract(context.Context, *MsgActivateCronContract) (*MsgActivateCronContractResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ActivateCronContract not implemented")
}
func (UnimplementedMsgServer) mustEmbedUnimplementedMsgServer() {}

// UnsafeMsgServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to MsgServer will
// result in compilation errors.
type UnsafeMsgServer interface {
	mustEmbedUnimplementedMsgServer()
}

func RegisterMsgServer(s grpc.ServiceRegistrar, srv MsgServer) {
	s.RegisterService(&Msg_ServiceDesc, srv)
}

func _Msg_UpdateParams_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(MsgUpdateParams)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MsgServer).UpdateParams(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Msg_UpdateParams_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MsgServer).UpdateParams(ctx, req.(*MsgUpdateParams))
	}
	return interceptor(ctx, in, info, handler)
}

func _Msg_RegisterCronContract_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(MsgRegisterCronContract)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MsgServer).RegisterCronContract(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Msg_RegisterCronContract_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MsgServer).RegisterCronContract(ctx, req.(*MsgRegisterCronContract))
	}
	return interceptor(ctx, in, info, handler)
}

func _Msg_UnregisterCronContract_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(MsgUnregisterCronContract)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MsgServer).UnregisterCronContract(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Msg_UnregisterCronContract_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MsgServer).UnregisterCronContract(ctx, req.(*MsgUnregisterCronContract))
	}
	return interceptor(ctx, in, info, handler)
}

func _Msg_ActivateCronContract_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(MsgActivateCronContract)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MsgServer).ActivateCronContract(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Msg_ActivateCronContract_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MsgServer).ActivateCronContract(ctx, req.(*MsgActivateCronContract))
	}
	return interceptor(ctx, in, info, handler)
}

// Msg_ServiceDesc is the grpc.ServiceDesc for Msg service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var Msg_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "wasmapp.onchainkeeper.Msg",
	HandlerType: (*MsgServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "UpdateParams",
			Handler:    _Msg_UpdateParams_Handler,
		},
		{
			MethodName: "RegisterCronContract",
			Handler:    _Msg_RegisterCronContract_Handler,
		},
		{
			MethodName: "UnregisterCronContract",
			Handler:    _Msg_UnregisterCronContract_Handler,
		},
		{
			MethodName: "ActivateCronContract",
			Handler:    _Msg_ActivateCronContract_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "wasmapp/onchainkeeper/tx.proto",
}
